-- One table holds everything about an upload: where the file is, how far
-- processing has got, and the results. It is also the job queue: the worker
-- looks for rows whose status is not finished.

CREATE TABLE IF NOT EXISTS jobs (
    id            UUID PRIMARY KEY,       -- generated by the API, also used as the file name in the bucket

    -- the upload
    filename      TEXT NOT NULL,          -- original name, shown in the UI
    storage_path  TEXT NOT NULL,          -- object key inside the storage bucket
    size_bytes    BIGINT NOT NULL,
    language      TEXT NOT NULL,          -- language code sent to Gnani, e.g. en-IN

    -- processing state
    status        TEXT NOT NULL DEFAULT 'QUEUED'
                  CHECK (status IN ('QUEUED', 'TRANSCRIBING', 'SUMMARIZING', 'COMPLETED', 'FAILED')),
    gnani_job_id  TEXT,                   -- saved so a restarted worker can resume instead of starting over
    gnani_status  TEXT,                   -- Gnani's own status for that job (CREATED, QUEUED, IN_PROGRESS, ...)
    error         TEXT,                   -- user-readable reason when something went wrong

    -- results
    transcript    TEXT,
    summary       TEXT,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    queued_at     TIMESTAMPTZ NOT NULL DEFAULT now(),  -- reset on retry; the timeout is measured from here
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()   -- last time the worker touched the row
);

-- The history page lists newest first.
CREATE INDEX IF NOT EXISTS jobs_created_at_idx ON jobs (created_at DESC);
